services:
  - type: web
    name: tiktok-live-monitor
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start

    envVars:
      - key: NODE_VERSION
        value: "20"

      - key: MIN_SECONDS
        value: "30"
